### ISSUE TITLE
Error when running DeRR.py

### ISSUE THREAD

**Issue by JingwenD** [GuoBioinfoLab/DeRR#1]
Hi,
Thanks for developing this cool tool for TCR analysis.
I got an error when running `python DeRR.py`:

`FileNotFoundError: [Errno 2] No such file or directory: '/workspace/chensy/dual/0.Script/deer/reference/temp/AIRR-V-short.fa'`

My conda environment is created according to the `readme.md` with python3.7.
Could you help me with this issue? Looking forwards to your reply.
Best,
JD

**Comment by aqzas** [comment]
Sorry for the late reply
This error is caused by wrong path to the reference genome, and it's my fault not mentioned it in README. You have to change the path in `config.json` to fix it or using new version of DeRR.
